Fix resource bundle signing error when archiving with Xcode 14 beta
Resolves: https://github.com/tuist/tuist/issues/4568

- Archiving resources bundles when using Xcode 14 beta results in a code signing error as Xcode attempts to codesign it (whereas it didn't before)

```
error: Signing for "A_A" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'A_A' from project 'A')
```

- The `CODE_SIGNING_ALLOWED` default value appears to have changed to `YES` for bundle targets in Xcode 14 (it used to be `NO` in Xcode 13), which appears to be causing this issue
- To mitigate this, we can explicitly set the `CODE_SIGNING_ALLOWED` to `NO` for generated resource targets
  - This should be backwards compatible with Xcode 13

Notes:

- An additional change is required to XcodeProj to ensure any bundle target for iOS has this as a default recommended setting to account for manually created resource bundle targets

Test Plan:

- Run `swift build` to build this version of Tuist
- Generate a fixture that contains a resource bundle that is automatically generated by Tuist

```sh
swift run tuist generate --path ./projects/tuist/fixtures/ios_app_with_static_frameworks_with_resources
```

- Select the resource bundle scheme (e.g. `A_A`) and attempt to archive it on Xcode 13 and Xcode 14
- Verify it successfully archives without issues

References:

- https://developer.apple.com/forums/thread/708659

`A_A` is a generated resource bundle target.

```sh
$ xcrun xcodebuild -showBuildSettings -workspace App.xcworkspace -scheme A_A | grep CODE_SIGN
    AD_HOC_CODE_SIGNING_ALLOWED = NO
    CODE_SIGNING_ALLOWED = NO
    CODE_SIGNING_REQUIRED = YES
    CODE_SIGN_CONTEXT_CLASS = XCiPhoneOSCodeSignContext
    CODE_SIGN_IDENTITY = iPhone Developer
    CODE_SIGN_INJECT_BASE_ENTITLEMENTS = YES
    EXPANDED_CODE_SIGN_IDENTITY =
    EXPANDED_CODE_SIGN_IDENTITY_NAME =
    __CODE_SIGNING_ALLOWED_appletvos = NO
    __CODE_SIGNING_ALLOWED_iphoneos = NO
    __CODE_SIGNING_ALLOWED_watchos = NO
```

```sh
$ DEVELOPER_DIR=/Applications/Xcode14-beta2.app/Contents/Developer/ xcrun xcodebuild -showBuildSettings -workspace App.xcworkspace -scheme A_A | grep CODE_SIGN
    AD_HOC_CODE_SIGNING_ALLOWED = NO
    CODE_SIGNING_ALLOWED = YES
    CODE_SIGNING_REQUIRED = YES
    CODE_SIGN_CONTEXT_CLASS = XCiPhoneOSCodeSignContext
    CODE_SIGN_IDENTITY = iPhone Developer
    CODE_SIGN_INJECT_BASE_ENTITLEMENTS = YES
    EXPANDED_CODE_SIGN_IDENTITY =
    EXPANDED_CODE_SIGN_IDENTITY_NAME =
```