Remove directories from archive to fix permissions issues (#1237)
`swift package resolve` fails with the following errors when using the
archives uploaded by our server:
```
error: 'Alamofire.Alamofire': failed extracting '/Users/marekfort/Library/Caches/org.swift.swiftpm/registry/downloads/Alamofire/Alamofire/5.10.2.zip' to '/Users/marekfort/Library/Caches/org.swift.swiftpm/registry/downloads/Alamofire/Alamofire/5.10.2': Error Domain=NSCocoaErrorDomain Code=257 "The file “DE08D407-61E5-4FF9-8294-A8D19F13C5BE” couldn’t be opened because you don’t have permission to view it." UserInfo={NSUserStringVariant=(
    Folder
), NSURL=file:///Users/marekfort/Library/Caches/org.swift.swiftpm/registry/downloads/Alamofire/Alamofire/DE08D407-61E5-4FF9-8294-A8D19F13C5BE, NSFilePath=/Users/marekfort/Library/Caches/org.swift.swiftpm/registry/downloads/Alamofire/Alamofire/DE08D407-61E5-4FF9-8294-A8D19F13C5BE, NSUnderlyingError=0x60000349f5a0 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}}
```

The issue is that the archive returned from GitHub includes also
directories. In Elixir, those are represented as tuples with no contents
`{~c"path-to-dir", ""}`. The fix is to filter those out as the archive
doesn't need explicit directory references.

The only gotcha is that the current implementation also skips empty
files as we have no way to distinguish empty files and directories, but
that should be fine (I believe).

Unfortunately, this means we will need to repopulate the packages again.