Fix acceptance test failures due to build tool plugins (#5404)
- The acceptance tests were failing on main with the following error:

```
Validate plug-in “SwiftLintPlugin” in package “swiftlint”
error: “SwiftLintPlugin” must be enabled before it can be used
```

- This is due to one of the fixtures leveraging a build tool plugin (`ios_app_with_actions`)
- Xcode requires users to validate and trust plugins before it can load and use them
- This is typically a user prompt in the Xcode UI
- On CI however additional paramters are needed to the `xcodebuild` commands to skip this prompt

References:

- https://forums.swift.org/t/telling-xcode-14-beta-4-to-trust-build-tool-plugins-programatically/59305/7